### ISSUE TITLE
你好，自编译请教

### ISSUE THREAD

**Issue by jiaoyilun** [SudaMod/android_packages_apps_Dialer#1]
你好，请教一下，com.a1os.cloud.phone.PhoneUtil这个类在哪里，能否开源

**Comment by ghbhaha** [comment]
https://github.com/SudaMod/android_external_suda_SudaSDKs/tree/sm-1.1/libSudaLocation 发自网易邮箱手机版 在2015年10月20日 22:03 ，JIaoYilun写道： 你好，请教一下，com.a1os.cloud.phone.PhoneUtil这个类在哪里，能否开源 — Reply to this email directly or view it on GitHub.

**Comment by ghbhaha** [comment]
https://github.com/SudaMod/android_external_suda_SudaSDKs/tree/sm-1.1/libSudaLocation

**Comment by hyne-shan** [comment]
https://github.com/SudaMod/android_packages_apps_Dialer/issues/1
